// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// draw_cat
int draw_cat(NumericVector prob);
RcppExport SEXP _ConsensusVelo_draw_cat(SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(draw_cat(prob));
    return rcpp_result_gen;
END_RCPP
}
// k_sample_cpp
IntegerVector k_sample_cpp(NumericMatrix Prob);
RcppExport SEXP _ConsensusVelo_k_sample_cpp(SEXP ProbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Prob(ProbSEXP);
    rcpp_result_gen = Rcpp::wrap(k_sample_cpp(Prob));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ConsensusVelo_draw_cat", (DL_FUNC) &_ConsensusVelo_draw_cat, 1},
    {"_ConsensusVelo_k_sample_cpp", (DL_FUNC) &_ConsensusVelo_k_sample_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ConsensusVelo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
