# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

draw_cat <- function(prob) {
    .Call(`_ConsensusVelo_draw_cat`, prob)
}

k_sample_cpp <- function(Prob) {
    .Call(`_ConsensusVelo_k_sample_cpp`, Prob)
}

